# CI项目
name: OWRT-ALL

# CI计划
on:
  # 自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI权限
permissions: write-all

# CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [X86] # 可以根据需要添加更多配置
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [owrt]

    # 调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_THEME: argon
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST}}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run handles script
        run: |
          chmod +x handles.sh
          ./handles.sh

      - name: Build and install packages
        run: |
          make package/feeds/packages/luci-app-openvpn-server/compile
          make package/install
