# CI项目
name: QCA-ALL

# CI计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI权限
permissions: write-all

# CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    steps:
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup install stable
          rustup default stable
          rustup update stable

      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          docker-images: true
          large-packages: true
          swap-storage: true
          tool-cache: true

      - name: Remove Packages
        run: |
          sudo apt-get remove --autoremove -y $pkgs || echo "::warning::Failed to remove packages. Proceeding..."
          sudo apt-get clean || echo "::warning::Failed to clean packages. Proceeding..."

      - name: Call WRT-CORE Workflow
        uses: ./.github/workflows/WRT-CORE.yml
        with:
          WRT_TARGET: ${{matrix.CONFIG}}
          WRT_THEME: argon
          WRT_NAME: OWRT
          WRT_SSID: OWRT
          WRT_WORD: 12345678
          WRT_IP: 192.168.10.1
          WRT_PW: 无
          WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
          WRT_BRANCH: ${{matrix.BRANCH}}
          WRT_SOURCE: ${{matrix.SOURCE}}
          WRT_PACKAGE: ${{inputs.PACKAGE}}
          WRT_TEST: ${{inputs.TEST}}
