name: QCA-ALL

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_THEME: argon
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST}}

  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Disk Space and Memory
        run: |
          df -h
          free -m

      - name: Remove unnecessary packages
        run: |
          retry() {
            local n=1
            local max=5
            local delay=5
            while true; do
              "$@" && break || {
                if [[ $n -lt $max ]]; then
                  ((n++))
                  echo "Command failed. Attempt $n/$max:"
                  sleep $delay;
                else
                  echo "The command has failed after $n attempts."
                  return 1
                }
              }
            done
          }

          gcloud_prerm=$(cat << 'EOF'
          #!/bin/sh
          set -e
          apt-get remove --autoremove -y google-cloud-cli
          EOF
          )
          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli-anthoscli.prerm > /dev/null
          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli.prerm > /dev/null

          pkgs="dos2unix libfuse-dev"
          retry sudo apt-get remove --autoremove -y $pkgs
          retry sudo apt-get clean
