steps:
  - name: Check available disk space before remove
    run: df -h

  - name: Remove unnecessary packages
    run: |
      if dpkg -l | grep -q 'google-cloud-cli-anthoscli'; then
        gcloud_prerm='#!/bin/sh
        echo $0
        if [ -d "/usr/lib/google-cloud-sdk" ]; then
          sudo rm -rf /usr/lib/google-cloud-sdk
        fi'
        
        echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli-anthoscli.prerm >/dev/null
        
        if ! sudo apt-get remove --autoremove -y google-cloud-cli-anthoscli; then
          echo "::warning::Failed to remove google-cloud-cli-anthoscli. Proceeding..."
        fi
      else
        echo "google-cloud-cli-anthoscli not installed"
      fi

  - name: Clean up
    run: |
      if ! sudo apt-get clean; then
        echo "::warning::Failed to clean up"
      fi
      sudo rm -rf /var/lib/apt/lists/*
      df -h

  - name: Check available disk space after clean-up
    run: df -h
